### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by xhendrikg** [LiterallyFabian/MSPet.js#1]
C:\Users\USER\Desktop\MSPet.js-master\midi-osu>node start
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\USER\Desktop\MSPet.js-master\midi-osu\start'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []

**Comment by LiterallyFabian** [comment]
Oops I forgot to change the URL when pasting the readme from another of my repositories, sorry about that. Should be correct now, keep in mind it will only work on Swedish servers unless you change the urls & username manually;

https://github.com/LiterallyFabian/MSPet.js/blob/7e1e743c7f52c3a5defa06035320f026589db998/index.js#L27

**Comment by xhendrikg** [comment]
hi thanks for the fast edit. I did that and now i still got some errors: C:\Users\USER\Desktop\MSPet.js-master\MSPet.js-master>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2021-08-23T18_55_01_249Z-debug.log

**Comment by xhendrikg** [comment]
and when im in the MSPet.js-master folder I cant do cd MSPet.js (is it because github adds the '-master'?)

**Comment by LiterallyFabian** [comment]
Fixed in 2da8051f535f2e6dc0116b1f6cf613cc4ead02e6, thanks! You can start it with `node index.js` or pull and use `npm start`.

`cd` is just changing the directory your terminal is working from, if it adds `-master` to the directory name you can either rename the directory or change the command

**Comment by xhendrikg** [comment]
thanks!! now im at the msp2 se server and it says my password is wrong or username

**Comment by xhendrikg** [comment]
hmm im on the se server and the "fast login" says im "DE". Can i get swedish with a vpn?

**Comment by xhendrikg** [comment]
k i need to use an vpn

**Comment by LiterallyFabian** [comment]
Accounts are tied to a server - if you created your account on DE you will not be able to use it on other servers as they're technically different games, I don't think VPNs or similar will work. 

I could probably fix the ability to change server someday, but it's nothing I can promise since I haven't tested it on other servers, the petting might work differently between regions.

**Comment by xhendrikg** [comment]
> if you created your account on DE you will not be able to use it on other servers

I created a new one

> I don't think VPNs or similar will work.

They do

I run the tool but didnt got anything, It said petting (...) some times and i dont know if i got anything

**Comment by xhendrikg** [comment]
I tried a second time. I got the petting (some id) text and nothing happened. I relogged and nothing happened :(

**Comment by LiterallyFabian** [comment]
Seems like MSP will accept some requests without actually processing them, tried the tool with some friends and we have gotten it to work 3 out of 4 times. A bit hard to debug it though, since in the end the tool is just trying to mimic requests that the user petted something while they actually never did. I'm afraid I can't help you much more though since I don't have much info to work with.

**Comment by xhendrikg** [comment]
I petted some pet myself and now it works

**Comment by LiterallyFabian** [comment]
Sweet!
