### ISSUE TITLE
dont work for me

### ISSUE THREAD

**Issue by xhendev** [LiterallyFabian/MSPet.js#8]
Hello,

i changed all links with se or SE to de but it doesnt work for me. i changed the pet ids and tried many user ids. Can u try make it work?

**Comment by LiterallyFabian** [comment]
hey, everything seems to be working fine for me;
![image](https://user-images.githubusercontent.com/47401343/134804652-4fc6a3da-c732-462d-8d09-08c964dab926.png)

And nothing related to the authorization or petting has been changed since your last issues or your [fork](https://github.com/xhendev/MSPet.js) got updated, so I'm afraid I can't do much here. You could try logging the entire fetch-response and see if MSP gives you any additional errors, but I doubt it considering their API isn't supposed to be used like this.

**Comment by xhendev** [comment]
Did you used the german server and vpn?

**Comment by xhendev** [comment]
and changed the urls in the code etc

**Comment by LiterallyFabian** [comment]
No, I've only tried it on the Swedish server, but they all run the same software & version. VPNs doesn't matter as accounts are tied to a domain/server.

**Comment by xhendev** [comment]
when u use the german website and german vpn u are on the german server and not swedish

**Comment by xhendev** [comment]
i changed everything to de and it doesnt work for me
can u try it?

**Comment by LiterallyFabian** [comment]
> when u use the german website and german vpn u are on the german server and not swedish

Yes, German site = German server. VPN, geolocation and stuff like that doesn't matter. 

Could potentially give it an attempt someday, but then I will have to create a new account, gather pet IDs etc but again, I haven't touched the code since you last successfully ran it.

**Comment by LiterallyFabian** [comment]
> When im on moviestarplanet2.se i can login on my german account. 

Yes, because you picked the German server. It's not more complex than that.

> So like i said u need a vpn lol

Like I have already told you 4 times earlier, no, a VPN is not needed "lol".

The only thing that matters is what server you pick on the website, maybe your VPN did that for you automatically or maybe you did it yourself, but IP/VPN/geolocation doesn't do any difference for the game itself. 

![image](https://user-images.githubusercontent.com/47401343/135643333-3e0f7100-1e74-4cb3-97a0-59ab3d842030.png)
